version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortner-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis_password 
    depends_on:
      - redis
    networks:
      - mynetwork 

  redis:
    image: redis/redis-stack:latest
    container_name: redis_db
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--requirepass", "redis_password"] 
    networks:
      - mynetwork 

volumes:
  redis-data:

networks:
  mynetwork:  # Define a custom network
    driver: bridge